// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-xDGFzX-fx7ZWia6TuEqnQixvwazhTM',
    appId: '1:1092620325512:web:b462c4da2ab9db8a41053d',
    messagingSenderId: '1092620325512',
    projectId: 'binkelime-48ecb',
    authDomain: 'binkelime-48ecb.firebaseapp.com',
    storageBucket: 'binkelime-48ecb.firebasestorage.app',
    measurementId: 'G-E60SMTR84H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFOlOw3HLA_K_tfIx8oXP9G56dSOOGsk',
    appId: '1:1092620325512:android:fb361c734ecdd04741053d',
    messagingSenderId: '1092620325512',
    projectId: 'binkelime-48ecb',
    storageBucket: 'binkelime-48ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHcfsyEXyLqADFbkLhzz8mZPbVA7ZKcgo',
    appId: '1:1092620325512:ios:e6c95d54ab06f93f41053d',
    messagingSenderId: '1092620325512',
    projectId: 'binkelime-48ecb',
    storageBucket: 'binkelime-48ecb.firebasestorage.app',
    iosBundleId: 'com.ic.binkelime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHcfsyEXyLqADFbkLhzz8mZPbVA7ZKcgo',
    appId: '1:1092620325512:ios:e6c95d54ab06f93f41053d',
    messagingSenderId: '1092620325512',
    projectId: 'binkelime-48ecb',
    storageBucket: 'binkelime-48ecb.firebasestorage.app',
    iosBundleId: 'com.ic.binkelime',
  );
}
